[build]
builder = "heroku/buildpacks:20"
buildCommand = "mvn clean package -DskipTests && java -jar target/car_rental_services-0.0.1-SNAPSHOT.jar"

[deploy]
startCommand = "java -jar target/*.jar"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300

[variables]
SPRING_DATASOURCE_URL = "jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}"
