[build]
builder = "nixpacks"
buildCommand = "chmod +x mvnw && ./mvnw package -DskipTests"

[deploy]
startCommand = "java -jar target/*.jar"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300
