server:
  port: 8807

management:
  endpoints:
    web:
      exposure:
        include: health, info
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        readiness:
          include: custom
  health:
    db:
      enabled: false
    defaults:
      enabled: false
    custom:
      enabled: true

spring:
  application:
    name: Car Rental Services

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

admin:
  email: www.faizullahkhan.com.in@gmail.com

logging:
  level:
    root: INFO
    com.project.car_rental_services: DEBUG
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.boot.actuate: DEBUG
