server:
  port: 8807

spring:
  application:
    name: Car Rental Services

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql.railway.internal:3306/railway
    username: root
    password: nLsxqRWsYOLMNNHBhPcdSDFnFzLsnUNY

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: faizullahkhan.com.in@gmail.com
    password: mjgn aqhu awgw pgtl

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

admin:
  email: www.faizullahkhan.com.in@gmail.com #write your email here for testing
#email: www.beingpriyanshu5555@gmail.com